name: ${DOCKER_COMPOSE_PROJECT_NAME}

services:
  nuxt:
    build: .
    restart: unless-stopped
    ports:
      - ":3000"
    # command: "npm run start"
    labels:
      - traefik.enable=true
      - traefik.http.routers.${TRAEFIK_ROUTER_NAME:-xmrchatnuxt}.rule=Host(`${DOMAIN_NAME:-xmrchat.com}`)
      - traefik.http.routers.${TRAEFIK_ROUTER_NAME:-xmrchatnuxt}.entrypoints=websecure
      - traefik.http.routers.${TRAEFIK_ROUTER_NAME:-xmrchatnuxt}.tls=true
      - traefik.http.routers.${TRAEFIK_ROUTER_NAME:-xmrchatnuxt}.tls.certresolver=myresolver
      - traefik.http.services.${TRAEFIK_ROUTER_NAME:-xmrchatnuxt}.loadbalancer.server.port=3000
    networks:
      - traefik
    env_file: .env
networks:
  traefik:
    name: traefik
    external: true
