services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    volumes:
      - ./test-results:/app/test-results
    depends_on:
      - nuxt
    env_file:
      - .env
    network_mode: host

