services:
  postgres:
    image: postgres:14-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  postgres-backup:
    image: postgres:14-alpine
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./backups:/backups
    entrypoint: >
      sh -c "
      mkdir -p /backups &&
      while true; do
        sleep 10
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -U $$POSTGRES_USER -h postgres $$POSTGRES_DB > /backups/backup-$$(date +%Y%m%d%H%M%S).sql &&
        echo Backup created at $(date) &&
        ls -1 /backups/*.sql | head -n -4 | xargs rm -f
        sleep 300;
      done
      "

  redis:
    image: redis/redis-stack:latest
    ports:
      - ${REDIS_PORT}:6379

    volumes:
      - ./redis/data:/data

  minio:
    image: quay.io/minio/minio
    ports:
      - ${MINIO_PORT}:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}

    volumes:
      - ./minio/data:/data

    command: server /data --console-address ":9001"

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  signal-cli:
    image: bbernhard/signal-cli-rest-api
    ports:
      - '8080:8080'
    volumes:
      - ./signal-cli:/home/.local/share/signal-cli
    environment:
      - MODE=native
  
  simplex:
    build:
      context: ./docker/simplex
      dockerfile: Dockerfile
    ports:
      - "5225:5225"
    volumes:
      - ./simplex:/root/.simplex
    restart: no
