name: Build dev

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          load: true
          tags: xmrchat-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build server image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          load: true
          tags: xmrchat-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save client image
        run: docker save -o client-image.tar xmrchat-client:latest

      - name: Save server image
        run: docker save -o server-image.tar xmrchat-server:latest

      - name: Send client image
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: client-image.tar
          target: /tmp

      - name: Send server image
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: server-image.tar
          target: /tmp

      - name: Load and run docker
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            #!/bin/bash
            set -e

            echo "Loading and deploying client..."
            docker load < /tmp/client-image.tar
            cd /projnew/xmrchat-dev/client
            docker-compose up -d

            echo "Loading and deploying server..."
            docker load < /tmp/server-image.tar
            cd /projnew/xmrchat-dev/server
            docker-compose up -d
